platform :ios, '8.0'
target ‘TTJF’  do
inhibit_all_warnings!
pod 'AFNetworking', '~> 3.1.0'
pod 'PPNetworkHelper', '~> 0.4.0'
#pod 'ReactiveCocoa', '~> 2.0.1'
#pod 'MMProgressHUD', '~> 0.3.2'
#pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
#pod 'AMap3DMap'
#pod 'AMapSearch'
pod 'SDCycleScrollView', '~> 1.65'
#pod 'UMengSocialCOM', '~> 5.2.1'
pod 'POP+MCAnimate', '2.0.1'
pod 'UMengAnalytics', '3.5.10'
#pod 'hpple'
pod 'FontAwesome+iOS', '~> 0.1.4'
#pod 'ReactiveCocoa'
pod 'TTTAttributedLabel', '1.13.4'
pod 'RegexKitLite-NoWarning', '1.1.0'
#pod 'TouchJSON'
pod 'FMDB'
pod 'IQKeyboardManager'
    
pod 'Masonry', '~> 1.1.0'
pod 'EAIntroView'
pod 'SMPageControl', '~> 1.2'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKPlatforms/Copy'
pod 'ShareSDK3/ShareSDKPlatforms/SMS'
pod 'ShareSDK3/ShareSDKExtension'

pod 'XHLaunchAd', '~> 3.4.4'

pod 'ReactiveObjC'

end
